
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package gramatica_respuestas;

/** CUP generated class containing symbol constants. */
public class ParserRespuestasSym {
  /* terminals */
  public static final int RESPUESTA = 34;
  public static final int ELIMINAR_COMPONENTE = 26;
  public static final int MENOR = 6;
  public static final int LLAVES_FIN = 3;
  public static final int ELIMINAR_FORMULARIO = 21;
  public static final int NUEVO_FORMULARIO = 20;
  public static final int CREDENCIALES_USUARIO = 19;
  public static final int MODIFICAR_COMPONENTE = 25;
  public static final int CORCHETES_FIN = 5;
  public static final int CONSULTAS = 30;
  public static final int LLAVES_INICIO = 2;
  public static final int FIN_RESPUESTA = 13;
  public static final int INICIO_RESPUESTA = 12;
  public static final int PARAMETROS_COMPONENTE = 27;
  public static final int ELIMINAR_USUARIO = 17;
  public static final int PARAMETROS_FORMULARIO = 23;
  public static final int CREAR_USUARIO = 15;
  public static final int DOS_PUNTOS = 9;
  public static final int COMA = 10;
  public static final int MAYOR = 7;
  public static final int EOF = 0;
  public static final int AGREGAR_COMPONENTE = 24;
  public static final int FIN_RESPUESTAS = 14;
  public static final int EXCLAMACION = 8;
  public static final int error = 1;
  public static final int LOGIN_USUARIO = 18;
  public static final int VALOR_TEXTO = 31;
  public static final int CONSULTAR_DATOS = 28;
  public static final int TABLA_CONSULTA = 29;
  public static final int MODIFICAR_FORMULARIO = 22;
  public static final int PARAMETRO = 33;
  public static final int INICIO_RESPUESTAS = 11;
  public static final int MODIFICAR_USUARIO = 16;
  public static final int VALOR = 32;
  public static final int CORCHETES_INICIO = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVES_INICIO",
  "LLAVES_FIN",
  "CORCHETES_INICIO",
  "CORCHETES_FIN",
  "MENOR",
  "MAYOR",
  "EXCLAMACION",
  "DOS_PUNTOS",
  "COMA",
  "INICIO_RESPUESTAS",
  "INICIO_RESPUESTA",
  "FIN_RESPUESTA",
  "FIN_RESPUESTAS",
  "CREAR_USUARIO",
  "MODIFICAR_USUARIO",
  "ELIMINAR_USUARIO",
  "LOGIN_USUARIO",
  "CREDENCIALES_USUARIO",
  "NUEVO_FORMULARIO",
  "ELIMINAR_FORMULARIO",
  "MODIFICAR_FORMULARIO",
  "PARAMETROS_FORMULARIO",
  "AGREGAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "ELIMINAR_COMPONENTE",
  "PARAMETROS_COMPONENTE",
  "CONSULTAR_DATOS",
  "TABLA_CONSULTA",
  "CONSULTAS",
  "VALOR_TEXTO",
  "VALOR",
  "PARAMETRO",
  "RESPUESTA"
  };
}
