
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package gramatica_reporteria;

/** CUP generated class containing symbol constants. */
public class ParserReporteriaSym {
  /* terminals */
  public static final int WHERE = 19;
  public static final int SQFORM_VALOR_NOMRE_CAMPOS = 22;
  public static final int MENOS = 8;
  public static final int AND = 13;
  public static final int MENOR = 4;
  public static final int SELECT = 16;
  public static final int OR = 14;
  public static final int IGUAL = 7;
  public static final int MENOR_IGUAL = 10;
  public static final int CORCHETES_FIN = 3;
  public static final int NOT = 15;
  public static final int MAYOR_IGUAL = 11;
  public static final int SQFORM_VALOR_TEXTO = 21;
  public static final int FORM = 18;
  public static final int ID = 12;
  public static final int COMA = 6;
  public static final int SQFORM_VALOR_NUMERO = 20;
  public static final int MAYOR = 5;
  public static final int EOF = 0;
  public static final int MENOR_MAYOR = 9;
  public static final int error = 1;
  public static final int TO = 17;
  public static final int CORCHETES_INICIO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CORCHETES_INICIO",
  "CORCHETES_FIN",
  "MENOR",
  "MAYOR",
  "COMA",
  "IGUAL",
  "MENOS",
  "MENOR_MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "ID",
  "AND",
  "OR",
  "NOT",
  "SELECT",
  "TO",
  "FORM",
  "WHERE",
  "SQFORM_VALOR_NUMERO",
  "SQFORM_VALOR_TEXTO",
  "SQFORM_VALOR_NOMRE_CAMPOS"
  };
}
