
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package gramatica_importacion_formularios;

/** CUP generated class containing symbol constants. */
public class ParserImportacionDatosSym {
  /* terminals */
  public static final int PARENTESIS_FIN = 5;
  public static final int PARENTESIS_INICIO = 4;
  public static final int BOTON = 37;
  public static final int ALINEACION = 24;
  public static final int PUBLICO = 15;
  public static final int VALOR_FECHA = 49;
  public static final int NOMBRE = 11;
  public static final int SI = 42;
  public static final int CHECKBOX = 32;
  public static final int WHITE = 18;
  public static final int DOS_PUNTOS = 6;
  public static final int IZQUIERDA = 39;
  public static final int ESTRUCTURA = 44;
  public static final int INDICE = 22;
  public static final int NEWFORMULARIO = 8;
  public static final int VALOR_ITEMS_SIN_ESPACIO = 47;
  public static final int CENTRO = 38;
  public static final int TITULO = 10;
  public static final int FICHERO = 34;
  public static final int LLAVES_INICIO = 2;
  public static final int EOF = 0;
  public static final int CLASE = 21;
  public static final int error = 1;
  public static final int DIGITO = 51;
  public static final int VALOR_ITEMS_CON_ESPACIO = 46;
  public static final int COMA = 7;
  public static final int URL = 29;
  public static final int VALOR_ID = 50;
  public static final int LLAVES_FIN = 3;
  public static final int ID_COMPONENTE = 20;
  public static final int FECHA_CREACION = 14;
  public static final int USUARIO_CREACION = 13;
  public static final int TEMA = 12;
  public static final int ID_FORMULARIO = 9;
  public static final int REQUERIDO = 25;
  public static final int NO = 43;
  public static final int RADIO = 33;
  public static final int DERECHA = 40;
  public static final int IMAGEN = 35;
  public static final int NOMBRE_CAMPO = 19;
  public static final int COMBO = 36;
  public static final int VALOR_TEXTO_VISIBLE_CON_ESPACIO = 45;
  public static final int BLUE = 17;
  public static final int DARK = 16;
  public static final int VALOR_PASSWORD = 48;
  public static final int COLUMNAS = 28;
  public static final int JUSTIFICAR = 41;
  public static final int FILAS = 27;
  public static final int AREA_TEXTO = 31;
  public static final int CAMPO_TEXTO = 30;
  public static final int TEXTO_VISIBLE = 23;
  public static final int OPCIONES = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVES_INICIO",
  "LLAVES_FIN",
  "PARENTESIS_INICIO",
  "PARENTESIS_FIN",
  "DOS_PUNTOS",
  "COMA",
  "NEWFORMULARIO",
  "ID_FORMULARIO",
  "TITULO",
  "NOMBRE",
  "TEMA",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "PUBLICO",
  "DARK",
  "BLUE",
  "WHITE",
  "NOMBRE_CAMPO",
  "ID_COMPONENTE",
  "CLASE",
  "INDICE",
  "TEXTO_VISIBLE",
  "ALINEACION",
  "REQUERIDO",
  "OPCIONES",
  "FILAS",
  "COLUMNAS",
  "URL",
  "CAMPO_TEXTO",
  "AREA_TEXTO",
  "CHECKBOX",
  "RADIO",
  "FICHERO",
  "IMAGEN",
  "COMBO",
  "BOTON",
  "CENTRO",
  "IZQUIERDA",
  "DERECHA",
  "JUSTIFICAR",
  "SI",
  "NO",
  "ESTRUCTURA",
  "VALOR_TEXTO_VISIBLE_CON_ESPACIO",
  "VALOR_ITEMS_CON_ESPACIO",
  "VALOR_ITEMS_SIN_ESPACIO",
  "VALOR_PASSWORD",
  "VALOR_FECHA",
  "VALOR_ID",
  "DIGITO"
  };
}
