
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package gramatica_indigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int USUARIO_ANTIGUO = 22;
  public static final int CONSULTAR_DATOS = 75;
  public static final int DARK = 36;
  public static final int MODIFICAR_FORMULARIO = 28;
  public static final int EXCLAMACION = 8;
  public static final int CAMPO_TEXTO = 54;
  public static final int TITULO = 31;
  public static final int IZQUIERDA = 63;
  public static final int FIN_SOLICITUDES = 14;
  public static final int LLAVES_INICIO = 2;
  public static final int VALOR_PASSWORD = 71;
  public static final int CHECKBOX = 56;
  public static final int MAYOR = 7;
  public static final int SI = 66;
  public static final int USUARIO_NUEVO = 23;
  public static final int FECHA_MODIFICACION = 25;
  public static final int USUARIO_CREACION = 34;
  public static final int BLUE = 37;
  public static final int VALOR_TEXTO_VISIBLE_CON_ESPACIO = 68;
  public static final int TEMA = 33;
  public static final int ELIMINAR_COMPONENTE = 41;
  public static final int CENTRO = 62;
  public static final int WHITE = 38;
  public static final int PASSWORD = 21;
  public static final int OPCIONES = 50;
  public static final int MODIFICAR_USUARIO = 16;
  public static final int CONSULTA_N = 77;
  public static final int VALOR_ITEMS_CON_ESPACIO = 69;
  public static final int ELIMINAR_USUARIO = 17;
  public static final int FICHERO = 58;
  public static final int TEXTO_VISIBLE = 47;
  public static final int DOS_PUNTOS = 9;
  public static final int CREAR_USUARIO = 15;
  public static final int FILAS = 51;
  public static final int NUEVO_PASSWORD = 24;
  public static final int AREA_TEXTO = 55;
  public static final int FORMULARIO = 44;
  public static final int ELIMINAR_FORMULARIO = 27;
  public static final int COMA = 10;
  public static final int DIGITO = 74;
  public static final int VALOR_ITEMS_SIN_ESPACIO = 70;
  public static final int INICIO_SOLICITUD = 12;
  public static final int VALOR_FECHA = 72;
  public static final int CLASE = 45;
  public static final int VALOR_ID = 73;
  public static final int NOMBRE = 32;
  public static final int NOMBRE_CAMPO = 43;
  public static final int NUEVO_FORMULARIO = 26;
  public static final int LOGIN_USUARIO = 18;
  public static final int COLUMNAS = 52;
  public static final int FIN_SOLICITUD = 13;
  public static final int CORCHETES_FIN = 5;
  public static final int MENOR = 6;
  public static final int USUARIO = 20;
  public static final int CONSULTAS = 76;
  public static final int URL = 53;
  public static final int PARAMETROS_COMPONENTE = 42;
  public static final int EOF = 0;
  public static final int CORCHETES_INICIO = 4;
  public static final int MODIFICAR_COMPONENTE = 40;
  public static final int IMAGEN = 59;
  public static final int error = 1;
  public static final int CREDENCIALES_USUARIO = 19;
  public static final int BOTON = 61;
  public static final int JUSTIFICAR = 65;
  public static final int ID = 30;
  public static final int DERECHA = 64;
  public static final int RADIO = 57;
  public static final int FECHA_CREACION = 35;
  public static final int REQUERIDO = 49;
  public static final int PARAMETROS_FORMULARIO = 29;
  public static final int INICIO_SOLICITUDES = 11;
  public static final int COMBO = 60;
  public static final int INDICE = 46;
  public static final int ALINEACION = 48;
  public static final int NO = 67;
  public static final int LLAVES_FIN = 3;
  public static final int AGREGAR_COMPONENTE = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVES_INICIO",
  "LLAVES_FIN",
  "CORCHETES_INICIO",
  "CORCHETES_FIN",
  "MENOR",
  "MAYOR",
  "EXCLAMACION",
  "DOS_PUNTOS",
  "COMA",
  "INICIO_SOLICITUDES",
  "INICIO_SOLICITUD",
  "FIN_SOLICITUD",
  "FIN_SOLICITUDES",
  "CREAR_USUARIO",
  "MODIFICAR_USUARIO",
  "ELIMINAR_USUARIO",
  "LOGIN_USUARIO",
  "CREDENCIALES_USUARIO",
  "USUARIO",
  "PASSWORD",
  "USUARIO_ANTIGUO",
  "USUARIO_NUEVO",
  "NUEVO_PASSWORD",
  "FECHA_MODIFICACION",
  "NUEVO_FORMULARIO",
  "ELIMINAR_FORMULARIO",
  "MODIFICAR_FORMULARIO",
  "PARAMETROS_FORMULARIO",
  "ID",
  "TITULO",
  "NOMBRE",
  "TEMA",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "DARK",
  "BLUE",
  "WHITE",
  "AGREGAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "ELIMINAR_COMPONENTE",
  "PARAMETROS_COMPONENTE",
  "NOMBRE_CAMPO",
  "FORMULARIO",
  "CLASE",
  "INDICE",
  "TEXTO_VISIBLE",
  "ALINEACION",
  "REQUERIDO",
  "OPCIONES",
  "FILAS",
  "COLUMNAS",
  "URL",
  "CAMPO_TEXTO",
  "AREA_TEXTO",
  "CHECKBOX",
  "RADIO",
  "FICHERO",
  "IMAGEN",
  "COMBO",
  "BOTON",
  "CENTRO",
  "IZQUIERDA",
  "DERECHA",
  "JUSTIFICAR",
  "SI",
  "NO",
  "VALOR_TEXTO_VISIBLE_CON_ESPACIO",
  "VALOR_ITEMS_CON_ESPACIO",
  "VALOR_ITEMS_SIN_ESPACIO",
  "VALOR_PASSWORD",
  "VALOR_FECHA",
  "VALOR_ID",
  "DIGITO",
  "CONSULTAR_DATOS",
  "CONSULTAS",
  "CONSULTA_N"
  };
}
